apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-node-app
  labels:
    app: basic-node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: basic-node-app
  template:
    metadata:
      labels:
        app: basic-node-app
    spec:
      containers:
      - name: basic-node-app
        image: yashrajdighe/basic-node-app:V1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: basic-node-app
spec:
  type: ClusterIP
  selector:
    app: basic-node-app
  ports:
    - protocol: TCP
      port: 3000
